---
# tasks file for lb-tier

- name: Install HA Proxy
  package:
    name: haproxy
    state: latest

- name: Start and enable HA Proxy
  service:
    name: haproxy
    state: started
    enabled: true

- name: Deploy HA Proxy config
  template:
    src: haproxy.cfg.j2
    dest: "{{ lb_basedir }}/haproxy.cfg"
  notify:
    - restart haproxy
