---
# tasks file for app-tier

- name: Install Tomcat
  package:
    name: tomcat
    state: latest

- name: Start and enable tomcat
  service:
    name: tomcat
    state: started
    enabled: true

- name: Create the Tomcat dir
  file:
    path: "{{ apps_basedir }}"
    state: directory

- name: Deploy the index.html
  template:
    src: index.html.j2
    dest: "{{ apps_basedir }}/index.html"
    mode: 0644
  notify:
    - restart tomcat
