---
# tasks file for base-config

- name: Enable Sudo without TTY for Ansible
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes
